apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.environment }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.image.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.tier }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.environment }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.deployment.image.registry }}:{{ .Values.deployment.image.name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          livenessProbe:
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.deployment.livenessProbe.httpGet.path }}
              port: {{ .Values.service.port }}
              scheme: {{ .Values.deployment.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.deployment.readinessProbe.httpGet.path }}
              port: {{ .Values.service.port }}
              scheme: {{ .Values.deployment.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-cm-{{ .Values.environment }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
